first header added
DRother21/Modern-Cloud pull request #2
Opened 2024-03-17 21:08 UTC by ekoyn

How's the name of this header?

2024-03-17 23:48 UTC, DRother21 reviewed
Looks good to me!

2024-03-17 23:49 UTC, DRother21 requested changes, later dismissed
Changes?

2024-03-18 00:15 UTC, DRother21 reviewed
Review

2024-03-18 00:29 UTC, ekoyn commented on index.html
> +<h1>This is a header</h1>
Starting a new review

2024-03-18 00:29 UTC, DRother21 approved these changes
Here is a review

2024-03-18 00:29 UTC, DRother21 commented on index.html
> +<h1>This is a header</h1>
Review

2024-03-18 00:29 UTC, DRother21 commented on index.html
> +<h1>This is a header</h1>
Review

2024-03-18 00:30 UTC, ekoyn commented on index.html
> +<h1>This is a header</h1>
Ah yes, I'll make some edits

2024-03-18 00:32 UTC, DRother21 requested changes
Change Request

2024-03-18 00:47 UTC, DRother21 approved these changes

2024-03-18 00:49 UTC, merged